name: Generate Contribution Snake

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate contribution snake
        uses: github-contribution-grid-snake-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output_path: ./output/github-contribution-grid-snake.svg

      - name: Commit and push snake image
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add ./output/github-contribution-grid-snake.svg
          git commit -m "chore: update contribution snake [skip ci]" || echo "No changes to commit"
          git push
